INSERT INTO Artiste(nom) VALUES ('Remy Bourgeois');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Remy Bourgeois','Aube','audio/001-1512247-Remy_Bourgeois-Aube.mp3',26063,'img/covers/001-1512247-Remy_Bourgeois-Aube.mp3.jpg',NULL,'Ambient',NULL);
INSERT INTO Artiste(nom) VALUES ('DR GROOVE GANG');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'DR GROOVE GANG','Sweet Soul Musik','audio/001-1608790-DR_GROOVE_GANG-Sweet_Soul_Musik.mp3',42259,'img/covers/001-1608790-DR_GROOVE_GANG-Sweet_Soul_Musik.mp3.jpg',NULL,'Soul',NULL);
INSERT INTO Artiste(nom) VALUES ('George Capon');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'George Capon','Underground','audio/001-1667043-George_Capon-Underground.mp3',26693,'img/covers/001-1667043-George_Capon-Underground.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Eliot Feldman');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Eliot Feldman','Song Of My Life','audio/001-1711840-Eliot_Feldman-Song_Of_My_Life.mp3',12881,'img/covers/001-1711840-Eliot_Feldman-Song_Of_My_Life.mp3.jpg',NULL,'chillout',NULL);
INSERT INTO Artiste(nom) VALUES ('HonH');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'HonH','All Novels','audio/002-1551619-HonH-All_Novels.mp3',42683,'img/covers/002-1551619-HonH-All_Novels.mp3.jpg',NULL,'Rock',NULL);
INSERT INTO Artiste(nom) VALUES ('Axl &amp; Arth');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Axl &amp; Arth','Triumphant','audio/002-1672065-Axl__amp__Arth-Triumphant.mp3',12272,'img/covers/002-1672065-Axl__amp__Arth-Triumphant.mp3.jpg',NULL,'Electronic',NULL);
INSERT INTO Artiste(nom) VALUES ('Giovanni Scarpelli Band');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Giovanni Scarpelli Band','DARKNESS BEHIND','audio/002-1712352-Giovanni_Scarpelli_Band-DARKNESS_BEHIND.mp3',35710,'img/covers/002-1712352-Giovanni_Scarpelli_Band-DARKNESS_BEHIND.mp3.jpg',NULL,'alternativerock',NULL);
INSERT INTO Artiste(nom) VALUES ('Project Divinity');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Project Divinity','Second Awakening','audio/002-18234-Project_Divinity-Second_Awakening.mp3',18705,'img/covers/002-18234-Project_Divinity-Second_Awakening.mp3.jpg',NULL,'Ambient','Divinity');
INSERT INTO Artiste(nom) VALUES ('Tonepoet');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tonepoet','As The Sun Begins To Awake','audio/003-1530855-Tonepoet-As_The_Sun_Begins_To_Awake.mp3',22576,'img/covers/003-1530855-Tonepoet-As_The_Sun_Begins_To_Awake.mp3.jpg',NULL,'filmscore','Headspace');
INSERT INTO Artiste(nom) VALUES ('Banana Cream');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Banana Cream','Whenever is the Right Time','audio/003-1657646-Banana_Cream-Whenever_is_the_Right_Time.mp3',6174,'img/covers/003-1657646-Banana_Cream-Whenever_is_the_Right_Time.mp3.jpg',NULL,NULL,NULL);
INSERT INTO Artiste(nom) VALUES ('The Spin Wires');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Spin Wires','Night Life','audio/003-1674219-The_Spin_Wires-Night_Life.mp3',24680,'img/covers/003-1674219-The_Spin_Wires-Night_Life.mp3.jpg',NULL,'indierock',NULL);
INSERT INTO Artiste(nom) VALUES ('The Devil Music Co.');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Devil Music Co.','Acid (Redux)','audio/003-1711246-The_Devil_Music_Co.-Acid__Redux_.mp3',23432,'img/covers/003-1711246-The_Devil_Music_Co.-Acid__Redux_.mp3.jpg',NULL,'Indie',NULL);
INSERT INTO Artiste(nom) VALUES ('Kinematic');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Kinematic','5 O clock High','audio/004-1442028-Kinematic-5_O_clock_High.mp3',16068,'img/covers/004-1442028-Kinematic-5_O_clock_High.mp3.jpg',NULL,'Rock','Kites');
INSERT INTO Artiste(nom) VALUES ('Lewis');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Lewis','Coffee At Midnight (Acoustic)','audio/004-1691507-Lewis-Coffee_At_Midnight__Acoustic_.mp3',22243,'img/covers/004-1691507-Lewis-Coffee_At_Midnight__Acoustic_.mp3.jpg',NULL,NULL,NULL);
INSERT INTO Artiste(nom) VALUES ('Zell');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Zell','Streets   ','audio/014-924962-Zell-Streets___.mp3',18227,'img/covers/014-924962-Zell-Streets___.mp3.jpg',NULL,'filmscore','Malibu');
INSERT INTO Artiste(nom) VALUES ('Axel Antunes');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Axel Antunes','Nature World','audio/015-1452539-Axel_Antunes-Nature_World.mp3',26417,'img/covers/015-1452539-Axel_Antunes-Nature_World.mp3.jpg',NULL,'Pop','#1');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tonepoet','Gathering My Thoughts Into A Paper Bag','audio/015-1530537-Tonepoet-Gathering_My_Thoughts_Into_A_Paper_Bag.mp3',33543,'img/covers/015-1530537-Tonepoet-Gathering_My_Thoughts_Into_A_Paper_Bag.mp3.jpg',NULL,'filmscore','N/E/W/S');
INSERT INTO Artiste(nom) VALUES ('Vinyl Blast');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Vinyl Blast','Vinyl Blast - Don\'t Kill Me','audio/015-1634208-Vinyl_Blast-Vinyl_Blast_-_Don_t_Kill_Me.mp3',23976,'img/covers/015-1634208-Vinyl_Blast-Vinyl_Blast_-_Don_t_Kill_Me.mp3.jpg',NULL,'alternativerock',NULL);
INSERT INTO Artiste(nom) VALUES ('Charlie Mosbrook');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Charlie Mosbrook','Singout','audio/015-1719785-Charlie_Mosbrook-Singout.mp3',11217,'img/covers/015-1719785-Charlie_Mosbrook-Singout.mp3.jpg',NULL,'americana','Remember Who We Are');
INSERT INTO Artiste(nom) VALUES ('Solxis');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Solxis','Tidal Pool','audio/016-1119896-Solxis-Tidal_Pool.mp3',6627,'img/covers/016-1119896-Solxis-Tidal_Pool.mp3.jpg',NULL,'newage','Sounds + Nature Volume 2');
INSERT INTO Artiste(nom) VALUES ('The Ambient Light');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Ambient Light','When I Fade Out','audio/016-1666154-The_Ambient_Light-When_I_Fade_Out.mp3',22168,'img/covers/016-1666154-The_Ambient_Light-When_I_Fade_Out.mp3.jpg',NULL,NULL,NULL);
INSERT INTO Artiste(nom) VALUES ('Pokki DJ');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Pokki DJ','No Prayers','audio/016-1668075-Pokki_DJ-No_Prayers.mp3',12810,'img/covers/016-1668075-Pokki_DJ-No_Prayers.mp3.jpg',NULL,'futurebass','No Prayers');
INSERT INTO Artiste(nom) VALUES ('Elephant Funeral');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Elephant Funeral','Laurens Song','audio/016-1725968-Elephant_Funeral-Laurens_Song.mp3',11000,'img/covers/016-1725968-Elephant_Funeral-Laurens_Song.mp3.jpg',NULL,'singersongwriter',NULL);
INSERT INTO Artiste(nom) VALUES ('The Vow');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Vow','Caroline (strings)','audio/017-1560214-The_Vow-Caroline__strings_.mp3',16488,'img/covers/017-1560214-The_Vow-Caroline__strings_.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Lower Loveday');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Lower Loveday','Chains','audio/017-1681047-Lower_Loveday-Chains.mp3',24515,'img/covers/017-1681047-Lower_Loveday-Chains.mp3.jpg',NULL,'indierock',NULL);
INSERT INTO Artiste(nom) VALUES ('Elric Virtuoso');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Elric Virtuoso','INSECTOID','audio/017-1684658-Elric_Virtuoso-INSECTOID.mp3',48401,'img/covers/017-1684658-Elric_Virtuoso-INSECTOID.mp3.jpg',NULL,NULL,'NEUROSIS');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Project Divinity','Third Awakening','audio/017-18236-Project_Divinity-Third_Awakening.mp3',18704,'img/covers/017-18236-Project_Divinity-Third_Awakening.mp3.jpg',NULL,'Ambient','Divinity');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tonepoet','Dreaming Out Loud','audio/018-1530801-Tonepoet-Dreaming_Out_Loud.mp3',22251,'img/covers/018-1530801-Tonepoet-Dreaming_Out_Loud.mp3.jpg',NULL,'filmscore','Resonate / Reason Nitrate');
INSERT INTO Artiste(nom) VALUES ('Forget the Whale');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Forget the Whale','The Little Robot','audio/008-1434824-Forget_the_Whale-The_Little_Robot.mp3',39696,'img/covers/008-1434824-Forget_the_Whale-The_Little_Robot.mp3.jpg',NULL,'Rock','What I Tell Myself Vol. 2');
INSERT INTO Artiste(nom) VALUES ('Omonoko');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Omonoko','Wild Heart','audio/008-1609779-Omonoko-Wild_Heart.mp3',37079,'img/covers/008-1609779-Omonoko-Wild_Heart.mp3.jpg',NULL,NULL,'Wild Heart - EP');
INSERT INTO Artiste(nom) VALUES ('Lessky');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Lessky','Solteria','audio/008-1716230-Lessky-Solteria.mp3',40067,'img/covers/008-1716230-Lessky-Solteria.mp3.jpg',NULL,'trap',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Zell','Go   ','audio/008-924970-Zell-Go___.mp3',18222,'img/covers/008-924970-Zell-Go___.mp3.jpg',NULL,'Classical','Malibu');
INSERT INTO Artiste(nom) VALUES ('Pure Mids');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Pure Mids','Everything We Wanted','audio/009-1657649-Pure_Mids-Everything_We_Wanted.mp3',14576,'img/covers/009-1657649-Pure_Mids-Everything_We_Wanted.mp3.jpg',NULL,'indierock',NULL);
INSERT INTO Artiste(nom) VALUES ('Estudiante');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Estudiante','Jamas decirte adiós','audio/009-1699080-Estudiante-Jamas_decirte_adios.mp3',15959,'img/covers/009-1699080-Estudiante-Jamas_decirte_adios.mp3.jpg',NULL,'Latin',NULL);
INSERT INTO Artiste(nom) VALUES ('Summer Ash');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Summer Ash','Milkman','audio/009-1721344-Summer_Ash-Milkman.mp3',15506,'img/covers/009-1721344-Summer_Ash-Milkman.mp3.jpg',NULL,'trap',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Project Divinity','Inside a Cocoon','audio/009-18232-Project_Divinity-Inside_a_Cocoon.mp3',18704,'img/covers/009-18232-Project_Divinity-Inside_a_Cocoon.mp3.jpg',NULL,'Ambient','Divinity');
INSERT INTO Artiste(nom) VALUES ('Tunguska Electronic Music Society');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tunguska Electronic Music Society','imprum - yolo (live)','audio/010-1501042-Tunguska_Electronic_Music_Society-imprum_-_______live_.mp3',43206,'img/covers/010-1501042-Tunguska_Electronic_Music_Society-imprum_-_______live_.mp3.jpg',NULL,'Ambient','imprum - donbass live');
INSERT INTO Artiste(nom) VALUES ('BLC MIRROR CLB');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'BLC MIRROR CLB','The Flood','audio/010-1683589-BLC_MIRROR_CLB-The_Flood.mp3',15429,'img/covers/010-1683589-BLC_MIRROR_CLB-The_Flood.mp3.jpg',NULL,NULL,'blc mirror clb');
INSERT INTO Artiste(nom) VALUES ('Square a Saw');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Square a Saw','Fearless','audio/010-1717028-Square_a_Saw-Fearless.mp3',20317,'img/covers/010-1717028-Square_a_Saw-Fearless.mp3.jpg',NULL,'futurebass',NULL);
INSERT INTO Artiste(nom) VALUES ('Radio Star');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Radio Star','A Common Tale','audio/010-744648-Radio_Star-A_Common_Tale.mp3',38159,'img/covers/010-744648-Radio_Star-A_Common_Tale.mp3.jpg',NULL,'indierock','A Common Tale');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Remy Bourgeois','Bal De Nuit (Lullaby Version)','audio/011-1436063-Remy_Bourgeois-Bal_De_Nuit__Lullaby_Version_.mp3',25115,'img/covers/011-1436063-Remy_Bourgeois-Bal_De_Nuit__Lullaby_Version_.mp3.jpg',NULL,'filmscore',NULL);
INSERT INTO Artiste(nom) VALUES ('ikkubaru');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'ikkubaru','Memories','audio/004-1701987-ikkubaru-Memories.mp3',34624,'img/covers/004-1701987-ikkubaru-Memories.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Explosive Ear Candy');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Explosive Ear Candy','Miracles Like You','audio/007-1716102-Explosive_Ear_Candy-Miracles_Like_You.mp3',39090,'img/covers/007-1716102-Explosive_Ear_Candy-Miracles_Like_You.mp3.jpg',NULL,'poprock',NULL);
INSERT INTO Artiste(nom) VALUES ('Fresh Body Shop');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Fresh Body Shop','Hypnotic','audio/011-1568293-Fresh_Body_Shop-Hypnotic.mp3',19234,'img/covers/011-1568293-Fresh_Body_Shop-Hypnotic.mp3.jpg',NULL,'poprock','Maze');
INSERT INTO Artiste(nom) VALUES ('ShtrefalmeT');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'ShtrefalmeT','Metal Child','audio/014-1719384-ShtrefalmeT-Metal_Child.mp3',104411,'img/covers/014-1719384-ShtrefalmeT-Metal_Child.mp3.jpg',NULL,'groovemetal',NULL);
INSERT INTO Artiste(nom) VALUES ('MCKOOL');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'MCKOOL','Impression','audio/018-1634882-MCKOOL-Impression.mp3',19232,'img/covers/018-1634882-MCKOOL-Impression.mp3.jpg',NULL,'edm',NULL);
INSERT INTO Artiste(nom) VALUES ('Liv Margaret');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Liv Margaret','Oasis','audio/018-1666675-Liv_Margaret-Oasis.mp3',27384,'img/covers/018-1666675-Liv_Margaret-Oasis.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('The Plecs');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Plecs','Exennials','audio/018-1719303-The_Plecs-Exennials.mp3',12112,'img/covers/018-1719303-The_Plecs-Exennials.mp3.jpg',NULL,'poppunk','EP #3');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Lower Loveday','Is It Right?','audio/019-1559614-Lower_Loveday-Is_It_Right_.mp3',18671,'img/covers/019-1559614-Lower_Loveday-Is_It_Right_.mp3.jpg',NULL,'indierock',NULL);
INSERT INTO Artiste(nom) VALUES ('Midnight Préfou');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Midnight Préfou','Do you miss me','audio/019-1657984-Midnight_Prefou-Do_you_miss_me.mp3',34809,'img/covers/019-1657984-Midnight_Prefou-Do_you_miss_me.mp3.jpg',NULL,'Indie','Bubulle is dead');
INSERT INTO Artiste(nom) VALUES ('Absolution Free');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Absolution Free','Burn With Me','audio/019-1720870-Absolution_Free-Burn_With_Me.mp3',31690,'img/covers/019-1720870-Absolution_Free-Burn_With_Me.mp3.jpg',NULL,'heavymetal',NULL);
INSERT INTO Artiste(nom) VALUES ('Carter Vail');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Carter Vail','Pontiac','audio/020-1666184-Carter_Vail-Pontiac.mp3',34984,'img/covers/020-1666184-Carter_Vail-Pontiac.mp3.jpg',NULL,NULL,NULL);
INSERT INTO Artiste(nom) VALUES ('Professor Kliq');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Professor Kliq','Gnosis Hardware','audio/020-1688991-Professor_Kliq-Gnosis_Hardware.mp3',52780,'img/covers/020-1688991-Professor_Kliq-Gnosis_Hardware.mp3.jpg',NULL,NULL,'Entertainment System');
INSERT INTO Artiste(nom) VALUES ('Zhund');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Zhund','5 pointz','audio/020-1720662-Zhund-5_pointz.mp3',10116,'img/covers/020-1720662-Zhund-5_pointz.mp3.jpg',NULL,'electronica','Dusty');
INSERT INTO Artiste(nom) VALUES ('Michael Ellis');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Michael Ellis','Summer','audio/021-1407840-Michael_Ellis-Summer.mp3',40177,'img/covers/021-1407840-Michael_Ellis-Summer.mp3.jpg',NULL,'Rock','Tavis Vor');
INSERT INTO Artiste(nom) VALUES ('Seth Power');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Seth Power','Closure - Acoustic','audio/021-1649149-Seth_Power-Closure_-_Acoustic.mp3',14052,'img/covers/021-1649149-Seth_Power-Closure_-_Acoustic.mp3.jpg',NULL,'singersongwriter',NULL);
INSERT INTO Artiste(nom) VALUES ('Back On Earth');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Back On Earth','Streets Of Alesia','audio/021-1685833-Back_On_Earth-Streets_Of_Alesia.mp3',20344,'img/covers/021-1685833-Back_On_Earth-Streets_Of_Alesia.mp3.jpg',NULL,NULL,'Brighten');
INSERT INTO Artiste(nom) VALUES ('Parker');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Parker','Walk Home','audio/022-1635095-Parker-Walk_Home.mp3',31798,'img/covers/022-1635095-Parker-Walk_Home.mp3.jpg',NULL,'alternativerock','Debut');
INSERT INTO Artiste(nom) VALUES ('Hands of Attrition');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Hands of Attrition','I\'m Gone','audio/022-1721181-Hands_of_Attrition-I_m_Gone.mp3',19219,'img/covers/022-1721181-Hands_of_Attrition-I_m_Gone.mp3.jpg',NULL,'groovemetal',NULL);
INSERT INTO Artiste(nom) VALUES ('Kavi Jezzie Hockaday');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Kavi Jezzie Hockaday','On My Way','audio/023-1721815-Kavi_Jezzie_Hockaday-On_My_Way.mp3',34120,'img/covers/023-1721815-Kavi_Jezzie_Hockaday-On_My_Way.mp3.jpg',NULL,'singersongwriter',NULL);
INSERT INTO Artiste(nom) VALUES ('A la Mode');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'A la Mode','Mountaintop','audio/A_la_Mode_-_01_-_Mountaintop.mp3',126986,'img/covers/A_la_Mode_-_01_-_Mountaintop.mp3.jpg','2015-12-15 11:50:12',NULL,'A la mode');
INSERT INTO Artiste(nom) VALUES ('Broke For Free');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Broke For Free','Night Owl','audio/Broke_For_Free_-_01_-_Night_Owl.mp3',288778,'img/covers/Broke_For_Free_-_01_-_Night_Owl.mp3.jpg','2011-01-18 11:15:40','Electronic','Directionless EP');
INSERT INTO Artiste(nom) VALUES ('Chad Crouch');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Chad Crouch','By The Pond (Instrumental)','audio/Chad_Crouch_-_01_-_By_The_Pond_Instrumental.mp3',1022173,'img/covers/Chad_Crouch_-_01_-_By_The_Pond_Instrumental.mp3.jpg','2019-07-16 13:05:04','Classical','Field Report Vol I: Oaks Bottom (Instrumental)');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Chad Crouch','Algorithms','audio/Chad_Crouch_-_Algorithms.mp3',99174,'img/covers/Chad_Crouch_-_Algorithms.mp3.jpg','2019-09-13 14:44:36','Electronic','Arps');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Chad Crouch','Amaranthus','audio/Chad_Crouch_-_Amaranthus.mp3',496650,'img/covers/Chad_Crouch_-_Amaranthus.mp3.jpg','2019-04-16 14:41:12','Electronic','Ambient Atmospheres');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Chad Crouch','Bald Eagle','audio/Chad_Crouch_-_Bald_Eagle.mp3',239037,'img/covers/Chad_Crouch_-_Bald_Eagle.mp3.jpg','2018-05-10 17:46:21','Minimalism','Birds of Oaks Bottom: Piano Solos');
INSERT INTO Artiste(nom) VALUES ('Naezy (Pagalworld.name)');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Naezy (Pagalworld.name)','Lets Crack (Pagalworld.name)','audio/Lets_Crack_It_-_Naezy.mp3',14499,'img/covers/Lets_Crack_It_-_Naezy.mp3.jpg',NULL,'indian Pop','Lets Crack (Pagalworld.name)');
INSERT INTO Artiste(nom) VALUES ('RENAE');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'RENAE','Roses (Taurus)','audio/RENAE_-_Roses__Taurus_.mp3',35472,'img/covers/RENAE_-_Roses__Taurus_.mp3.jpg',NULL,NULL,NULL);
INSERT INTO Artiste(nom) VALUES ('SaReGaMa');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'SaReGaMa','Samadhi','audio/004-80884-SaReGaMa-Samadhi.mp3',14012,'img/covers/004-80884-SaReGaMa-Samadhi.mp3.jpg',NULL,'Ambient','Samadhi');
INSERT INTO Artiste(nom) VALUES ('The Verandas');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Verandas','Lemon Pop','audio/005-1119024-The_Verandas-Lemon_Pop.mp3',22699,'img/covers/005-1119024-The_Verandas-Lemon_Pop.mp3.jpg',NULL,'Rock','Deep Down');
INSERT INTO Artiste(nom) VALUES ('Fortadelis');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Fortadelis','Step To Eternity','audio/005-113554-Fortadelis-Step_To_Eternity.mp3',24859,'img/covers/005-113554-Fortadelis-Step_To_Eternity.mp3.jpg',NULL,'Ambient','Fortadelis');
INSERT INTO Artiste(nom) VALUES ('Sam Garbett');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Sam Garbett','Here With You','audio/005-1633324-Sam_Garbett-Here_With_You.mp3',37494,'img/covers/005-1633324-Sam_Garbett-Here_With_You.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Just Matthew');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Just Matthew','All The Way','audio/005-1715026-Just_Matthew-All_The_Way.mp3',22159,'img/covers/005-1715026-Just_Matthew-All_The_Way.mp3.jpg',NULL,'gangstarap',NULL);
INSERT INTO Artiste(nom) VALUES ('Phillip Traum and the Moral Sense');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Phillip Traum and the Moral Sense','Starved Was My Soul (Original Mix)','audio/006-1448436-Phillip_Traum_and_the_Moral_Sense-Starved_Was_My_Soul__Original_Mix_.mp3',32484,'img/covers/006-1448436-Phillip_Traum_and_the_Moral_Sense-Starved_Was_My_Soul__Original_Mix_.mp3.jpg',NULL,'Ambient','Starved Was My Soul');
INSERT INTO Artiste(nom) VALUES ('Ping Pong Club');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Ping Pong Club','Venetian Blinds','audio/006-1544358-Ping_Pong_Club-Venetian_Blinds.mp3',47233,'img/covers/006-1544358-Ping_Pong_Club-Venetian_Blinds.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Niki J Crawford');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Niki J Crawford','Mama Cried - Niki J Crawford - The Second Truth','audio/006-1675591-Niki_J_Crawford-Mama_Cried_-_Niki_J_Crawford_-_The_Second_Truth.mp3',22099,'img/covers/006-1675591-Niki_J_Crawford-Mama_Cried_-_Niki_J_Crawford_-_The_Second_Truth.mp3.jpg',NULL,'Soul','The Second Truth');
INSERT INTO Artiste(nom) VALUES ('Egor Budennyy');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Egor Budennyy','Astray','audio/006-1716109-Egor_Budennyy-Astray.mp3',32462,'img/covers/006-1716109-Egor_Budennyy-Astray.mp3.jpg',NULL,'Synthpop','X Tapes');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tonepoet','The Dream Is Now','audio/007-1530545-Tonepoet-The_Dream_Is_Now.mp3',13273,'img/covers/007-1530545-Tonepoet-The_Dream_Is_Now.mp3.jpg',NULL,'chillout','Soundtrack For Imaginary Spaces');
INSERT INTO Artiste(nom) VALUES ('THE DLX');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'THE DLX','Always','audio/007-1624864-THE_DLX-Always.mp3',8253,'img/covers/007-1624864-THE_DLX-Always.mp3.jpg',NULL,'singersongwriter',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'The Spin Wires','Just A Fling','audio/007-1638617-The_Spin_Wires-Just_A_Fling.mp3',24427,'img/covers/007-1638617-The_Spin_Wires-Just_A_Fling.mp3.jpg',NULL,'alternativerock',NULL);
INSERT INTO Artiste(nom) VALUES ('Tab');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tab','Revolving Door (feat.Lusty Apricot &amp; Elle Rose)','audio/011-1655483-Tab-Revolving_Door__feat.Lusty_Apricot__amp__Elle_Rose_.mp3',22074,'img/covers/011-1655483-Tab-Revolving_Door__feat.Lusty_Apricot__amp__Elle_Rose_.mp3.jpg',NULL,'filmscore','Revolving Door / Horizons');
INSERT INTO Artiste(nom) VALUES ('Black Siren');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Black Siren','Spell','audio/011-1717333-Black_Siren-Spell.mp3',38455,'img/covers/011-1717333-Black_Siren-Spell.mp3.jpg',NULL,'Blues',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Tonepoet','Bound By Light','audio/012-1530540-Tonepoet-Bound_By_Light.mp3',13025,'img/covers/012-1530540-Tonepoet-Bound_By_Light.mp3.jpg',NULL,'filmscore','Soundtrack For Imaginary Spaces');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'THE DLX','Always','audio/012-1624864-THE_DLX-Always.mp3',8253,'img/covers/012-1624864-THE_DLX-Always.mp3.jpg',NULL,'singersongwriter',NULL);
INSERT INTO Artiste(nom) VALUES ('AIRE');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'AIRE','Show Me','audio/012-1658149-AIRE-Show_Me.mp3',33469,'img/covers/012-1658149-AIRE-Show_Me.mp3.jpg',NULL,'artrock',NULL);
INSERT INTO Artiste(nom) VALUES ('Rude');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Rude','Never Let Me Down','audio/012-1717618-Rude-Never_Let_Me_Down.mp3',26659,'img/covers/012-1717618-Rude-Never_Let_Me_Down.mp3.jpg',NULL,'alternativerock',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Phillip Traum and the Moral Sense','The Moment Of Moonrise','audio/013-1412344-Phillip_Traum_and_the_Moral_Sense-The_Moment_Of_Moonrise.mp3',45218,'img/covers/013-1412344-Phillip_Traum_and_the_Moral_Sense-The_Moment_Of_Moonrise.mp3.jpg',NULL,'Ambient','The Wayshower');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Pure Mids','Maybe Its Alright','audio/013-1543332-Pure_Mids-Maybe_Its_Alright.mp3',19711,'img/covers/013-1543332-Pure_Mids-Maybe_Its_Alright.mp3.jpg',NULL,'Indie',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Liv Margaret','Oasis','audio/013-1666675-Liv_Margaret-Oasis.mp3',27384,'img/covers/013-1666675-Liv_Margaret-Oasis.mp3.jpg',NULL,'indiepop',NULL);
INSERT INTO Artiste(nom) VALUES ('Samie Bower');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Samie Bower','Skyline','audio/013-1719234-Samie_Bower-Skyline.mp3',26519,'img/covers/013-1719234-Samie_Bower-Skyline.mp3.jpg',NULL,'rnb',NULL);
INSERT INTO Artiste(nom) VALUES ('Singleton');
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Singleton','Ways (Storm is Near)','audio/014-1625676-Singleton-Ways__Storm_is_Near_.mp3',24862,'img/covers/014-1625676-Singleton-Ways__Storm_is_Near_.mp3.jpg',NULL,'alternativerock',NULL);
INSERT INTO Titre(nomArtiste, nom, url, duree, urlImage, dateSortie, genre, titreAlbum) VALUES ( 'Parker','Walk Home','audio/014-1635095-Parker-Walk_Home.mp3',31798,'img/covers/014-1635095-Parker-Walk_Home.mp3.jpg',NULL,'alternativerock','Debut');
